/**
 * 事件定义
 * @author dodo
 * @date 2020.05.09
 */

export const EVENT_AUTH = "EVENT_AUTH";
export const EVENT_ALERT = "EVENT_ALERT";
export const EVENT_UPDATE_ROOM_INFO = "EVENT_UPDATE_ROOM_INFO";
export const EVENT_UPDATE_ONLINE_USERS = "EVENT_UPDATE_ONLINE_USERS";
export const EVENT_ONLINE_USER = "EVENT_ONLINE_USER";
export const EVENT_OFFLINE_USER = "EVENT_OFFLINE_USER";
export const EVENT_PULL_MESSAGES = "EVENT_PULL_MESSAGES";
export const EVENT_PUSH_MESSAGE = "EVENT_PUSH_MESSAGE";
